### ISSUE TITLE
Found a new use case that is not possible with current implementation

### ISSUE THREAD

**Issue by zummenix** [UsiantsevStepanSaritasa/DownSwift#15]
I need to attach some kind of meaning to a part of a text, for example: `Don't have an account? *Sign Up*`. When user taps on a text I'll determine what character index was tapped and get an attribute that I'm interested in using: `func attribute(_ attrName: NSAttributedString.Key, at location: Int, effectiveRange range: NSRangePointer?) -> Any?`. Currently, I can determine that `Sign Up` part has a bold font and know that the user tapped there but it's not a clear solution.

New API proposal (no `DownSwiftConfig` anymore):
```swift
let downSwift = DownSwift()
downSwift.register(tag: "*", attributes: [NSAttributedString.Key.font: boldFont, NSAttributedString.Key.link: "sign_up"])
let attributedText = downSwift.parse("Don't have an account? *Sign Up*")
```

Alternative is to support markdown links (`DownSwiftConfig` should have `linkFont`, `linkColor`, `linkUnderline`):
```swift
let downSwift = DownSwift()
let attributedText = downSwift.parse("Don't have an account? [Sign Up](sign_up)")
```

The solution based on the first with support for markdown links (this I like the most):
```swift
let downSwift = DownSwift()
downSwift.register(tag: "*", attributes: [NSAttributedString.Key.font: boldFont, NSAttributedString.Key.underlineStyle: NSUnderlineStyle.single])
let attributedText = downSwift.parse("Don't have an account? *[Sign Up](sign_up)*")
```

**Comment by UsiantsevStepanSaritasa** [comment]
Text style area customisation has been redesigned in 0.0.8 release.
Thank you for your contribution!
